### ISSUE TITLE
Website down / repository mirrors?

### ISSUE THREAD

**Issue by adrobisch** [KXStudio/Website#13]
Hi,
I was playing around yesterday with Carla and the VST plugin bridge and its amazing, thx for all the work.
Right now the whole page (http://kxstudio.linuxaudio.org) and the repos seem to be down. Is that a known issue? 

In general, I was wondering if it would be a good idea to setup a repository mirror for such cases?

Cheers,
Andreas

**Comment by falkTX** [comment]
The entire linuxaudio.org is down, a network drive where the "home" folder resides is unavailable.
A mirror can be setup, but the main repos are not there. Pretty much everything still keeps working.

**Comment by falkTX** [comment]
And everything is back to normal again
